import { db } from "./db";
import { businesses } from "@shared/schema";
import { sql } from "drizzle-orm";

const mockBusinesses = [
  {
    id: "1",
    name: "The Green Garden",
    category: "restaurant",
    description: "Healthy vegetarian cuisine with organic ingredients",
    address: "123 Main St",
    city: "Downtown",
    phone: "(555) 123-4567",
    priceRange: "$$",
    rating: "4.5",
    cuisineType: "Vegetarian",
    dietaryOptions: ["vegetarian", "vegan", "gluten-free"],
    reservationsEnabled: true,
    averageWaitTime: 15,
  },
  {
    id: "2",
    name: "Spice Route",
    category: "restaurant",
    description: "Authentic Indian flavors with modern presentation",
    address: "456 Oak Ave",
    city: "Downtown",
    phone: "(555) 234-5678",
    priceRange: "$$",
    rating: "4.7",
    cuisineType: "Indian",
    dietaryOptions: ["vegetarian", "halal"],
    reservationsEnabled: true,
    averageWaitTime: 20,
  },
  {
    id: "3",
    name: "Sakura Japanese",
    category: "restaurant",
    description: "Traditional Japanese cuisine and sushi bar",
    address: "789 Cherry Ln",
    city: "Midtown",
    phone: "(555) 345-6789",
    priceRange: "$$$",
    rating: "4.8",
    cuisineType: "Japanese",
    dietaryOptions: ["gluten-free"],
    reservationsEnabled: true,
    averageWaitTime: 25,
  },
  {
    id: "4",
    name: "Brew & Bean",
    category: "cafe",
    description: "Artisan coffee roasters and fresh pastries",
    address: "321 Coffee St",
    city: "Downtown",
    phone: "(555) 456-7890",
    priceRange: "$",
    rating: "4.6",
    cuisineType: "Coffee Shop",
    dietaryOptions: ["vegetarian"],
    reservationsEnabled: false,
    averageWaitTime: 5,
  },
  {
    id: "5",
    name: "The Study Corner",
    category: "cafe",
    description: "Quiet cafe perfect for studying and working",
    address: "654 Library Rd",
    city: "University District",
    phone: "(555) 567-8901",
    priceRange: "$",
    rating: "4.4",
    cuisineType: "Coffee Shop",
    dietaryOptions: ["vegetarian", "vegan"],
    reservationsEnabled: false,
    averageWaitTime: 10,
  },
  {
    id: "6",
    name: "Budget Bites",
    category: "restaurant",
    description: "Affordable meals for students and families",
    address: "987 Value Ave",
    city: "University District",
    phone: "(555) 678-9012",
    priceRange: "$",
    rating: "4.2",
    cuisineType: "American",
    dietaryOptions: ["vegetarian"],
    reservationsEnabled: true,
    averageWaitTime: 10,
  },
  {
    id: "7",
    name: "Noodle House",
    category: "restaurant",
    description: "Handmade noodles and authentic Asian cuisine",
    address: "147 Wok Way",
    city: "Chinatown",
    phone: "(555) 789-0123",
    priceRange: "$",
    rating: "4.5",
    cuisineType: "Asian",
    dietaryOptions: ["vegetarian", "vegan"],
    reservationsEnabled: true,
    averageWaitTime: 15,
  },
  {
    id: "8",
    name: "Library Cafe",
    category: "cafe",
    description: "Books and beverages in a cozy setting",
    address: "258 Reading Ln",
    city: "University District",
    phone: "(555) 890-1234",
    priceRange: "$",
    rating: "4.3",
    cuisineType: "Coffee Shop",
    dietaryOptions: ["vegetarian"],
    reservationsEnabled: false,
    averageWaitTime: 5,
  },
  {
    id: "9",
    name: "Night Owl Lounge",
    category: "bar",
    description: "Craft cocktails and appetizers",
    address: "369 Night St",
    city: "Entertainment District",
    phone: "(555) 901-2345",
    priceRange: "$$",
    rating: "4.4",
    cuisineType: "Bar & Grill",
    dietaryOptions: ["vegetarian"],
    reservationsEnabled: true,
    averageWaitTime: 30,
  },
  {
    id: "10",
    name: "Mediterranean Delight",
    category: "restaurant",
    description: "Fresh Mediterranean cuisine with halal options",
    address: "741 Olive Blvd",
    city: "Downtown",
    phone: "(555) 012-3456",
    priceRange: "$$",
    rating: "4.6",
    cuisineType: "Mediterranean",
    dietaryOptions: ["halal", "vegetarian", "vegan"],
    reservationsEnabled: true,
    averageWaitTime: 20,
  },
];

export async function seedDatabase() {
  try {
    const existingBusinesses = await db.select().from(businesses);
    if (existingBusinesses.length === 0) {
      console.log("Seeding database with mock businesses...");
      await db.insert(businesses).values(mockBusinesses as any);
      console.log("Database seeded successfully!");
    } else {
      console.log("Database already has businesses, skipping seed.");
    }
  } catch (error) {
    console.error("Error seeding database:", error);
  }
}
